### ISSUE TITLE
Flow past sphere / initial coarsened meshes

### ISSUE THREAD

**Issue by jh66637** [exadg/exadg#664] opened 2024-05-29 07:52 UTC
I am having trouble using global coarsened meshes (be e.g. setting AdditionalCFDRefinementsAroundSource to 1 in co_rotating_vortex_pair/input.json). This worked some time ago.

To check where this stems from, I tried to run the flow past sphere, i.e. the only application I am aware of, that uses global coarsened initial meshes (independent of preconditioners). This application already crashes during mesh generation, but I am relatively sure there will be the same issues I have in the example given above. If someone that is familiar with these parts of the code could take a look, it would be great. Once everything works, I can add tests for both test cases :)

**Comment by kronbichler** [comment] 2024-06-05 14:34
I think I can reproduce. Do you mean this error:
```
--------------------------------------------------------
An error occurred in line <12236> of file </home/martin/deal/deal.II/source/grid/tria.cc> in function
    void dealii::Triangulation<3, 3>::set_all_manifold_ids(const types::manifold_id) [dim = 3, spacedim = 3]
The violated condition was: 
    n_cells() > 0
Additional information: 
    Error: set_all_manifold_ids() can not be called on an empty
    Triangulation.
```
I will investigate, I think I know what to do.

**Comment by jh66637** [comment] 2024-06-05 15:33
This is the first error I get. I fear this might not be the only problem though...

**Comment by kronbichler** [comment] 2024-06-06 08:28
I did fix the other error in FSI applications and I see different errors at least there, which is related more closely to what you describe:
```
--------------------------------------------------------
An error occurred in line <2441> of file </home/martin/deal/deal.II/include/deal.II/lac/precondition.h> in function
    EigenvalueInformation dealii::internal::estimate_eigenvalues(const EigenvalueAlgorithmAdditionalData<PreconditionerType> &, const MatrixType *, VectorType &, VectorType &, const unsigned int) [MatrixType = ExaDG::MultigridOperatorBase<2, float>, VectorType = dealii::LinearAlgebra::distributed::Vector<float>, PreconditionerType = ExaDG::JacobiPreconditioner<ExaDG::MultigridOperatorBase<2, float>>]
The violated condition was: 
    data.preconditioner.get() != nullptr
Additional information: 
    (none)
```
I will check that one as well, here it seems to be a different kind of problem, where some diagonal is not compute throughout the hierarchy. Not sure if that is the actual problem, but at least it's one problem we currently have :wink:

**Comment by jh66637** [comment] 2024-06-07 17:38
https://github.com/exadg/exadg/pull/667 fixes the flow past sphere testcase. It is strange since I do not see major differences in the setup of the INSE solver compared to the co_rotating_vortex_pair. Adjusting the input file as described above still gives me the following error:

```
An error occurred in line <408> of file </home/johannes/workspace/exadg/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp> in function
    ExaDG::MultigridPreconditionerBase<dim, Number, MultigridNumber_>::do_initialize_dof_handler_and_constraints(bool, unsigned int, const Map_DBC&, const Map_DBC_ComponentMask&, dealii::MGLevelObject<std::shared_ptr<const dealii::DoFHandler<dim> > >&, dealii::MGLevelObject<std::shared_ptr<dealii::AffineConstraints<number> > >&) [with int dim = 2; Number = double; MultigridNumber_ = float; ExaDG::MultigridPreconditionerBase<dim, Number, MultigridNumber_>::Map_DBC = std::map<unsigned int, std::shared_ptr<dealii::Function<2> >, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::shared_ptr<dealii::Function<2> > > > >; ExaDG::MultigridPreconditionerBase<dim, Number, MultigridNumber_>::Map_DBC_ComponentMask = std::map<unsigned int, dealii::ComponentMask>]::<lambda(unsigned int)>
The violated condition was: 
    level.h_level() < grid->coarse_triangulations.size()
Additional information: 
    The vector coarse_triangulations seems to have incorrect size.
```
Anyway. Knowing, the flow past sphere works helps a lot. This way I can more easily trace down the reason.

**Comment by kronbichler** [comment] 2024-06-07 19:10
Thank you for reporting. It can also be that we still have issues with the multigrid solver. Let me know if you want me to take a look.

**Comment by jh66637** [comment] 2024-06-07 19:54
It seems the problem is that the setup does not involve h multigrid and therefore, no coarse triangulations are built. In `do_initialize_dof_handler_and_constraints()` we still try to access the coarse triangulations. I tried to avoid this but this leads to another error:
```
An error occurred in line <1889> of file </home/johannes/workspace/dealii/include/deal.II/dofs/dof_handler.h> in function
    const dealii::IndexSet& dealii::DoFHandler<dim, spacedim>::locally_owned_mg_dofs(unsigned int) const [with int dim = 2; int spacedim = 2]
The violated condition was: 
    mg_number_cache.size() == this->get_triangulation().n_global_levels()
Additional information: 
    The level dofs are not set up properly! Did you call
    distribute_mg_dofs()?

Stacktrace:
-----------
#0  /home/johannes/workspace/dealii/build/lib/libdeal_II.g.so.9.6.0-pre: dealii::DoFHandler<2, 2>::locally_owned_mg_dofs(unsigned int) const
#1  /home/johannes/workspace/exadg/build/libexadg.so: void dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >::reinit<dealii::Quadrature<2>, float, dealii::Mapping<2, 2> >(dealii::Mapping<2, 2> const&, std::vector<dealii::DoFHandler<2, 2> const*, std::allocator<dealii::DoFHandler<2, 2> const*> > const&, std::vector<dealii::AffineConstraints<float> const*, std::allocator<dealii::AffineConstraints<float> const*> > const&, std::vector<dealii::Quadrature<2>, std::allocator<dealii::Quadrature<2> > > const&, dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >::AdditionalData const&)
#2  /home/johannes/workspace/exadg/build/libexadg.so: std::_Function_handler<void (unsigned int), ExaDG::MultigridPreconditionerBase<2, double, float>::initialize_matrix_free_objects()::{lambda(unsigned int)#1}>::_M_invoke(std::_Any_data const&, unsigned int&&)
```
If you find the time to have a look it would be great. I am not very familiar with this part of the code.

To reproduce set: co_rotating_vortex_pair/input.json AdditionalCFDRefinementsAroundSource=1.

**Comment by richardschu** [comment] 2024-06-10 09:11
Hi @jh66637 , maybe this does not help much, but I changed the setup in my applications and I had to:
`  // Update coarse_triangulations after adaptive refinement.`
`    // This is necessary, since we split create_triangulation_with_multigrid()`
`    // and the creation of the mapping.`
`    if(n_refine_bdry > 0 and this->param.involves_h_multigrid())`
`    {`
`      GridUtilities::create_coarse_triangulations_after_coarsening_and_refinement(`
`        *grid.triangulation,`
`        grid.periodic_face_pairs,`
`        grid.coarse_triangulations,`
`        grid.coarse_periodic_face_pairs,`
`        this->param.grid,`
`        false /* preserve_boundary_cells */);`
`    }`
in case of adaptive refinement on the boundary, when splitting the mesh creation and mapping setup steps.
Maybe this helps or gets you to the right spot :smile:

**Comment by jh66637** [comment] 2024-06-10 18:42
@kronbichler @richardschu Thank you for your help!

**Comment by nfehn** [comment] 2024-07-05 08:49
I wonder whether the code from comment https://github.com/exadg/exadg/issues/664#issuecomment-2155258527)

```
Assert(level.h_level() < grid->coarse_triangulations.size(), ...)
```
is a problem(bug in the multigrid preconditioner implementation?

At other places, we compute the number of h-levels like
```
unsigned int const n_h_levels = level_info.back().h_level() - level_info.front().h_level() + 1;
```

So I wonder whether we compute the "offset" correctly in the assert.

**Comment by nfehn** [comment] 2024-07-05 09:03
I will take a look at this.

**Comment by nfehn** [comment] 2024-07-05 11:07
The `h_level` and the offset seems to be correct.

**Comment by nfehn** [comment] 2024-07-25 13:01
@jh66637 I do not really have the overview of which problems we resolved so far and whether there are remaining ones from the present issue. How about closing the present issue and raising existing or new problems in a clean issue?

**Closed** 2024-07-26 04:17 UTC
